In [2]:
import pandas as pd
from pathlib import Path

In [4]:
df_GBA = pd.read_csv("/home/m40ista/Projects/pd-transcriptomics-convergence/data/raw/GSE315738/PRJNA1398870_SraRunTable.csv")

df_GBA

,Run,Assay Type,AvgSpotLen,Bases,batch,BioProject,BioSample,Bytes,cell_line,cell_type,...,Organism,Platform,ReleaseDate,create_date,version,Sample Name,sex,source_name,SRA Study,tissue
0,SRR36692424,RNA-Seq,300,9186938400,3,PRJNA1398870,SAMN54465241,2902943436,H1112 clone 2,midbrain dopaminergic neurons,...,Homo sapiens,ILLUMINA,2026-01-10T00:00:00Z,2026-01-06T12:29:00Z,1,GSM9436084,male,iPSC-neurons,SRP660051,iPSC-neurons
1,SRR36692425,RNA-Seq,300,7901799300,2,PRJNA1398870,SAMN54465242,2495923392,H1112 clone 2,midbrain dopaminergic neurons,...,Homo sapiens,ILLUMINA,2026-01-10T00:00:00Z,2026-01-06T12:31:00Z,1,GSM9436083,male,iPSC-neurons,SRP660051,iPSC-neurons
2,SRR36692426,RNA-Seq,300,7842261900,1,PRJNA1398870,SAMN54465243,2492933853,H1112 clone 2,midbrain dopaminergic neurons,...,Homo sapiens,ILLUMINA,2026-01-10T00:00:00Z,2026-01-06T12:29:00Z,1,GSM9436082,male,iPSC-neurons,SRP660051,iPSC-neurons
3,SRR36692427,RNA-Seq,300,8942155500,3,PRJNA1398870,SAMN54465244,2124971588,H4997 B3,midbrain dopaminergic neurons,...,Homo sapiens,ILLUMINA,2026-01-10T00:00:00Z,2026-01-06T12:29:00Z,1,GSM9436081,male,iPSC-neurons,SRP660051,iPSC-neurons
4,SRR36692428,RNA-Seq,300,9746277300,2,PRJNA1398870,SAMN54465245,2290245312,H4997 B3,midbrain dopaminergic neurons,...,Homo sapiens,ILLUMINA,2026-01-10T00:00:00Z,2026-01-06T12:29:00Z,1,GSM9436080,male,iPSC-neurons,SRP660051,iPSC-neurons
5,SRR36692429,RNA-Seq,300,7113433200,1,PRJNA1398870,SAMN54465246,1676454344,H4997 B3,midbrain dopaminergic neurons,...,Homo sapiens,ILLUMINA,2026-01-10T00:00:00Z,2026-01-06T12:30:00Z,1,GSM9436079,male,iPSC-neurons,SRP660051,iPSC-neurons
6,SRR36692433,RNA-Seq,300,9474149400,3,PRJNA1398870,SAMN54465250,2269819369,H4997 A4,midbrain dopaminergic neurons,...,Homo sapiens,ILLUMINA,2026-01-10T00:00:00Z,2026-01-06T12:30:00Z,1,GSM9436075,male,iPSC-neurons,SRP660051,iPSC-neurons
7,SRR36692434,RNA-Seq,300,9963864900,2,PRJNA1398870,SAMN54465251,2373695570,H4997 A4,midbrain dopaminergic neurons,...,Homo sapiens,ILLUMINA,2026-01-10T00:00:00Z,2026-01-06T12:30:00Z,1,GSM9436074,male,iPSC-neurons,SRP660051,iPSC-neurons
8,SRR36692435,RNA-Seq,300,10101483000,1,PRJNA1398870,SAMN54465252,2378616174,H4997 A4,midbrain dopaminergic neurons,...,Homo sapiens,ILLUMINA,2026-01-10T00:00:00Z,2026-01-06T12:30:00Z,1,GSM9436073,male,iPSC-neurons,SRP660051,iPSC-neurons
9,SRR36692440,RNA-Seq,300,7090214100,2,PRJNA1398870,SAMN54465257,1708758552,H4997 clone 6,midbrain dopaminergic neurons,...,Homo sapiens,ILLUMINA,2026-01-10T00:00:00Z,2026-01-06T12:29:00Z,1,GSM9436068,male,iPSC-neurons,SRP660051,iPSC-neurons
10,SRR36692441,RNA-Seq,300,9638997000,1,PRJNA1398870,SAMN54465258,2252153985,H4997 clone 6,midbrain dopaminergic neurons,...,Homo sapiens,ILLUMINA,2026-01-10T00:00:00Z,2026-01-06T12:31:00Z,1,GSM9436067,male,iPSC-neurons,SRP660051,iPSC-neurons
11,SRR36692445,RNA-Seq,300,10225974900,3,PRJNA1398870,SAMN54465235,2455229911,H4997 WTRev,midbrain dopaminergic neurons,...,Homo sapiens,ILLUMINA,2026-01-10T00:00:00Z,2026-01-06T12:30:00Z,1,GSM9436090,male,iPSC-neurons,SRP660051,iPSC-neurons
12,SRR36692446,RNA-Seq,300,8866795200,2,PRJNA1398870,SAMN54465236,2043456805,H4997 WTRev,midbrain dopaminergic neurons,...,Homo sapiens,ILLUMINA,2026-01-10T00:00:00Z,2026-01-06T12:29:00Z,1,GSM9436089,male,iPSC-neurons,SRP660051,iPSC-neurons
13,SRR36692447,RNA-Seq,300,10264256400,1,PRJNA1398870,SAMN54465237,2427336589,H4997 WTRev,midbrain dopaminergic neurons,...,Homo sapiens,ILLUMINA,2026-01-10T00:00:00Z,2026-01-06T12:31:00Z,1,GSM9436088,male,iPSC-neurons,SRP660051,iPSC-neurons
14,SRR36692448,RNA-Seq,300,9998490600,3,PRJNA1398870,SAMN54465262,2380128241,H4997 clone 2,midbrain dopaminergic neurons,...,Homo sapiens,ILLUMINA,2026-01-10T00:00:00Z,2026-01-06T12:30:00Z,1,GSM9436063,male,iPSC-neurons,SRP660051,iPSC-neurons
15,SRR36692449,RNA-Seq,300,10558869000,2,PRJNA1398870,SAMN54465263,2484643394,H4997 clone 2,midbrain dopaminergic neurons,...,Homo sapiens,ILLUMINA,2026-01-10T00:00:00Z,2026-01-06T12:34:00Z,1,GSM9436062,male,iPSC-neurons,SRP660051,iPSC-neurons
16,SRR36692450,RNA-Seq,300,10473222300,1,PRJNA1398870,SAMN54465264,2469119972,H4997 clone 2,midbrain dopaminergic neurons,...,Homo sapiens,ILLUMINA,2026-01-10T00:00:00Z,2026-01-06T12:30:00Z,1,GSM9436061,male,iPSC-neurons,SRP660051,iPSC-neurons
17,SRR36692454,RNA-Seq,300,10367553000,3,PRJNA1398870,SAMN54465268,2424191872,H4997 clone 1,midbrain dopaminergic neurons,...,Homo sapiens,ILLUMINA,2026-01-10T00:00:00Z,2026-01-06T12:29:00Z,1,GSM9436057,male,iPSC-neurons,SRP660051,iPSC-neurons
18,SRR36692455,RNA-Seq,300,7318087800,2,PRJNA1398870,SAMN54465269,1721849015,H4997 clone 1,midbrain dopaminergic neurons,...,Homo sapiens,ILLUMINA,2026-01-10T00:00:00Z,2026-01-06T12:29:00Z,1,GSM9436056,male,iPSC-neurons,SRP660051,iPSC-neurons
19,SRR36692456,RNA-Seq,300,8342164500,1,PRJNA1398870,SAMN54465270,1937861021,H4997 clone 1,midbrain dopaminergic neurons,...,Homo sapiens,ILLUMINA,2026-01-10T00:00:00Z,2026-01-06T12:29:00Z,1,GSM9436055,male,iPSC-neurons,SRP660051,iPSC-neurons
20,SRR36692460,RNA-Seq,300,9518134800,3,PRJNA1398870,SAMN54465274,2248388370,H1112 clone 3,midbrain dopaminergic neurons,...,Homo sapiens,ILLUMINA,2026-01-10T00:00:00Z,2026-01-06T12:33:00Z,1,GSM9436051,male,iPSC-neurons,SRP660051,iPSC-neurons
21,SRR36692461,RNA-Seq,300,8788851900,2,PRJNA1398870,SAMN54465275,2093388099,H1112 clone 3,midbrain dopaminergic neurons,...,Homo sapiens,ILLUMINA,2026-01-10T00:00:00Z,2026-01-06T12:29:00Z,1,GSM9436050,male,iPSC-neurons,SRP660051,iPSC-neurons
22,SRR36692462,RNA-Seq,300,10454781000,1,PRJNA1398870,SAMN54465276,2477689734,H1112 clone 3,midbrain dopaminergic neurons,...,Homo sapiens,ILLUMINA,2026-01-10T00:00:00Z,2026-01-06T12:30:00Z,1,GSM9436049,male,iPSC-neurons,SRP660051,iPSC-neurons
23,SRR36692469,RNA-Seq,300,8670866400,3,PRJNA1398870,SAMN54465283,2064147272,H1112 clone 1,midbrain dopaminergic neurons,...,Homo sapiens,ILLUMINA,2026-01-10T00:00:00Z,2026-01-06T12:29:00Z,1,GSM9436042,male,iPSC-neurons,SRP660051,iPSC-neurons
24,SRR36692470,RNA-Seq,300,9633447300,2,PRJNA1398870,SAMN54465284,2328282920,H1112 clone 1,midbrain dopaminergic neurons,...,Homo sapiens,ILLUMINA,2026-01-10T00:00:00Z,2026-01-06T12:33:00Z,1,GSM9436041,male,iPSC-neurons,SRP660051,iPSC-neurons

In [ ]:
metadata = df_GBA[['Run', 'genotype']].rename(columns={
    'Run': 'sample',
    'genotype': 'comparison'
})

         sample    comparison
0   SRR36692424      GBA1 +/+ (Controles Saudáveis / Wild Type)
1   SRR36692425      GBA1 +/+ (Controles Saudáveis / Wild Type)
2   SRR36692426      GBA1 +/+ (Controles Saudáveis / Wild Type)
3   SRR36692427  GBA1 IVS/IVS (Mutante Homozigoto Nulo)
4   SRR36692428  GBA1 IVS/IVS (Mutante Homozigoto Nulo)
5   SRR36692429  GBA1 IVS/IVS (Mutante Homozigoto Nulo)
6   SRR36692433    GBA1 IVS/+ (Mutante Heterozigoto)
7   SRR36692434    GBA1 IVS/+ (Mutante Heterozigoto)
8   SRR36692435    GBA1 IVS/+ (Mutante Heterozigoto)
9   SRR36692440    GBA1 IVS/+ (Mutante Heterozigoto)
10  SRR36692441    GBA1 IVS/+ (Mutante Heterozigoto)
11  SRR36692445      GBA1 +/+ (Controles Saudáveis / Wild Type)
12  SRR36692446      GBA1 +/+ (Controles Saudáveis / Wild Type)
13  SRR36692447      GBA1 +/+ (Controles Saudáveis / Wild Type)
14  SRR36692448    GBA1 IVS/+ (Mutante Heterozigoto)
15  SRR36692449    GBA1 IVS/+ (Mutante Heterozigoto)
16  SRR36692450    GBA1 IVS/+ (Mutante Heterozigoto)
17  SRR36692454    GBA1 IVS/+ (Mutante Heterozigoto)
18  SRR36692455    GBA1 IVS/+ (Mutante Heterozigoto)
19  SRR36692456    GBA1 IVS/+ (Mutante Heterozigoto)
20  SRR36692460      GBA1 +/+ (Controles Saudáveis / Wild Type)
21  SRR36692461      GBA1 +/+ (Controles Saudáveis / Wild Type)
22  SRR36692462      GBA1 +/+ (Controles Saudáveis / Wild Type)
23  SRR36692469      GBA1 +/+ (Controles Saudáveis / Wild Type)
24  SRR36692470      GBA1 +/+ (Controles Saudáveis / Wild Type)

In [10]:
conditions = {
    'Control': 'GBA1 +/+ (Controles Saudáveis / Wild Type)',
    'Mutant': ['GBA1 IVS/+ (Mutante Heterozigoto)', 'GBA1 IVS/IVS (Mutante Homozigoto Nulo)']
}
metadata['condition'] = metadata['comparison'].map(lambda x: 'Control' if x == 'GBA1 +/+ (Controles Saudáveis / Wild Type)' else 'Mutant')

metadata.to_csv("/home/m40ista/Projects/pd-transcriptomics-convergence/data/processed/GBA/GBA_metadata.csv", index=False)